// =================================================================================
// == THIS IS THE ONLY FILE YOU WILL EVER EDIT ==
//
// Use your new `input.html` tool to generate the code, then paste the new line here.
// =================================================================================
const picksDatabase = [
    // --- TEMPLATE (Generated by your form) ---
    // { date: 'YYYY-MM-DD', team: 'TEAM NAME HERE', line: 0, result: 'W' },

    // --- PASTE YOUR NEW, GENERATED LINES AT THE TOP OF THIS LIST ---

    // --- YOUR COMPLETE, VERIFIED HISTORY (Most Recent First) ---
    { date: '2025-07-12', team: 'Blue Jays ML', line: -157, result: 'L' },
    // ... all 92 other historical picks ...
    { date: '2025-05-30', team: 'Giants Moneyline', line: -160, result: 'W' },
];
