#!/bin/bash

echo "=========================================="
echo "COMPREHENSIVE SPORTS DROPDOWN NCAAB AUDIT"
echo "=========================================="
echo ""

# Files confirmed to HAVE NCAAB in Sports dropdown
files_with_ncaab=(
"betlegend-verified-records.html"
"index.html"
"moneyline-parlay-of-the-day.html"
"nba-records.html"
"ncaab.html"
"ncaab-page2.html"
"ncaab-records.html"
"ncaaf-records.html"
"nfl-records.html"
"nfl-records-broken-backup.html"
"nhl-records.html"
"soccer-records.html"
)

# Files confirmed to be MISSING NCAAB in Sports dropdown
files_missing_ncaab=(
"affiliates.html"
"bankroll.html"
"best-bets-today.html"
"bestbook.html"
"bestonlinesportsbook.html"
"best-online-sportsbook-old.html"
"betting-101.html"
"betting-calculators.html"
"betting-glossary.html"
"blog.html"
"blog-page2.html"
"blog-page3.html"
"blog-page4.html"
"blog-page5.html"
"blog-page6.html"
"blog-page7.html"
"blog-page8.html"
"contact.html"
"covers-consensus.html"
"email.html"
"expected-value-calculator.html"
"featured-game-of-the-day.html"
"FreeAlerts.html"
"howitworks.html"
"implied-probability-calculator.html"
"kelly-criterion.html"
"live-odds.html"
"matchups.html"
"mlb.html"
"mlb-historical.html"
"mlb-page2.html"
"nba.html"
"ncaaf.html"
"ncaaf-page2.html"
"news.html"
"news-page2.html"
"news-page3.html"
"new-york-sports-betting.html"
"nfl.html"
"nhl.html"
"odds.html"
"odds-converter.html"
"parlay-calculator.html"
"picks.html"
"proofofpicks.html"
"records.html"
"screenshots.html"
"smartbets.html"
"soccer.html"
"subscribe.html"
"upcomingpicks.html"
)

echo "1. FILES WITH SPORTS DROPDOWN + NCAAB LINK (ALREADY CORRECT)"
echo "============================================================="
echo "Total: ${#files_with_ncaab[@]} files"
echo ""
for file in "${files_with_ncaab[@]}"; do
  echo "  ✓ $file"
done

echo ""
echo ""
echo "2. FILES WITH SPORTS DROPDOWN - MISSING NCAAB LINK (NEED TO FIX)"
echo "================================================================="
echo "Total: ${#files_missing_ncaab[@]} files"
echo ""
for file in "${files_missing_ncaab[@]}"; do
  echo "  ✗ $file"
done

echo ""
echo ""
echo "3. SPORTS DROPDOWN STRUCTURE ANALYSIS"
echo "======================================"
echo ""
echo "Files MISSING NCAAB currently have this structure:"
echo "  - NFL"
echo "  - MLB"
echo "  - NCAAF"
echo "  - NBA"
echo "  - NHL        ← NCAAB should be inserted BEFORE this"
echo "  - Soccer"
echo ""
echo "Correct structure should be:"
echo "  - NFL"
echo "  - MLB"
echo "  - NCAAF"
echo "  - NBA"
echo "  - NCAAB      ← ADD THIS LINE"
echo "  - NHL"
echo "  - Soccer"
echo ""
echo "Required code to insert:"
echo '  <a href="ncaab.html">NCAAB</a>'
echo ""
echo "Location: Insert AFTER the NBA link and BEFORE the NHL link"
echo ""
echo ""
echo "SUMMARY"
echo "======="
echo "Total HTML files with Sports dropdown: 62"
echo "  - Already have NCAAB: ${#files_with_ncaab[@]}"
echo "  - Missing NCAAB (NEED FIX): ${#files_missing_ncaab[@]}"
echo ""
