#!/usr/bin/env python3
"""
Regenerate NCAAF calendar data by extracting dates from each page.
"""

import os
import re
from pathlib import Path
from datetime import datetime

REPO = Path(r'C:\Users\Nima\nimadamus.github.io')

def extract_date_from_page(filepath):
    """Extract date from page title or content."""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    # Try to find date in title
    title_match = re.search(r'<title>([^<]+)</title>', content)
    title = title_match.group(1) if title_match else ''

    # Look for date patterns in title
    date_patterns = [
        r'December\s+(\d{1,2}),?\s+2025',
        r'November\s+(\d{1,2}),?\s+2025',
        r'October\s+(\d{1,2}),?\s+2025',
        r'(\d{4})-(\d{2})-(\d{2})',
    ]

    for pattern in date_patterns:
        match = re.search(pattern, title, re.IGNORECASE)
        if match:
            if len(match.groups()) == 3:
                # YYYY-MM-DD format
                return f"{match.group(1)}-{match.group(2)}-{match.group(3)}"
            else:
                # Month Day, Year format
                day = match.group(1)
                if 'december' in title.lower():
                    return f"2025-12-{int(day):02d}"
                elif 'november' in title.lower():
                    return f"2025-11-{int(day):02d}"
                elif 'october' in title.lower():
                    return f"2025-10-{int(day):02d}"

    # Try to find date in meta description
    desc_match = re.search(r'<meta\s+content="([^"]+)"\s+name="description"', content)
    if desc_match:
        desc = desc_match.group(1)
        for pattern in date_patterns[:3]:
            match = re.search(pattern, desc, re.IGNORECASE)
            if match:
                day = match.group(1)
                if 'december' in desc.lower():
                    return f"2025-12-{int(day):02d}"
                elif 'november' in desc.lower():
                    return f"2025-11-{int(day):02d}"
                elif 'october' in desc.lower():
                    return f"2025-10-{int(day):02d}"

    # Try hero section
    hero_match = re.search(r'class="hero-badge"[^>]*>([^<]+)', content)
    if hero_match:
        hero_text = hero_match.group(1)
        # Could be "Rivalry Week" or date info

    # Look for game dates in content
    game_dates = re.findall(r'2025-(\d{2})-(\d{2})', content)
    if game_dates:
        # Use the first game date found
        month, day = game_dates[0]
        return f"2025-{month}-{day}"

    return None

def get_title_from_page(filepath):
    """Extract title from page."""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    title_match = re.search(r'<title>([^<]+)</title>', content)
    if title_match:
        title = title_match.group(1)
        # Clean up title
        title = title.replace(' | BetLegend', '').strip()
        return title
    return filepath.stem

def main():
    pages = []

    # Main page
    if (REPO / 'ncaaf.html').exists():
        pages.append('ncaaf.html')

    # Numbered pages
    for f in sorted(REPO.glob('ncaaf-page*.html'), key=lambda x: int(re.search(r'(\d+)', x.name).group(1))):
        pages.append(f.name)

    print(f"Found {len(pages)} NCAAF pages")

    # Extract dates
    entries = []
    for page in pages:
        filepath = REPO / page
        date = extract_date_from_page(filepath)
        title = get_title_from_page(filepath)

        if date:
            entries.append({
                'date': date,
                'page': page,
                'title': title
            })
            print(f"  {page}: {date} - {title}")
        else:
            print(f"  {page}: NO DATE FOUND - {title}")
            # Assign a placeholder date based on file mod time
            mtime = os.path.getmtime(filepath)
            date = datetime.fromtimestamp(mtime).strftime('%Y-%m-%d')
            entries.append({
                'date': date,
                'page': page,
                'title': title
            })

    # Sort by date (newest first)
    entries.sort(key=lambda x: x['date'], reverse=True)

    # Generate JS file
    js_content = '''// NCAAF Archive Calendar Data
// Last updated: {today}
// Auto-generated by fix_ncaaf_calendar.py

const ARCHIVE_DATA = [
{entries}
];

const dateMap = {{}};
ARCHIVE_DATA.forEach(item => {{ if (!dateMap[item.date]) dateMap[item.date] = item; }});

const pageToDateMap = {{}};
ARCHIVE_DATA.forEach(item => {{ pageToDateMap[item.page] = item.date; }});

const currentPage = window.location.pathname.split('/').pop() || 'index.html';
const currentPageDate = pageToDateMap[currentPage] || null;

const months = new Set();
ARCHIVE_DATA.forEach(item => {{ const [y, m] = item.date.split('-'); months.add(y + '-' + m); }});

const today = new Date();
const currentMonth = today.getFullYear() + '-' + String(today.getMonth() + 1).padStart(2, '0');
const todayStr = today.getFullYear() + '-' + String(today.getMonth() + 1).padStart(2, '0') + '-' + String(today.getDate()).padStart(2, '0');
months.add(currentMonth);

const sortedMonths = Array.from(months).sort().reverse();
const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

let displayMonth = currentMonth;
if (currentPageDate) {{ const [py, pm] = currentPageDate.split('-'); displayMonth = py + '-' + pm; }}

function renderCalendar(yearMonth) {{
    const [year, month] = yearMonth.split('-').map(Number);
    const yearEl = document.getElementById('cal-year');
    if (yearEl) yearEl.textContent = year;
    const firstDay = new Date(year, month - 1, 1).getDay();
    const daysInMonth = new Date(year, month, 0).getDate();
    const container = document.getElementById('calendar-days');
    if (!container) return;
    container.innerHTML = '';
    for (let i = 0; i < firstDay; i++) {{ const cell = document.createElement('div'); cell.className = 'cal-day empty'; container.appendChild(cell); }}
    for (let d = 1; d <= daysInMonth; d++) {{
        const dateStr = year + '-' + String(month).padStart(2, '0') + '-' + String(d).padStart(2, '0');
        const hasData = dateMap[dateStr];
        let classes = 'cal-day';
        if (dateStr === todayStr) classes += ' today';
        if (dateStr === currentPageDate) classes += ' current-page';
        if (hasData) classes += ' has-content';
        const cell = document.createElement('div');
        cell.className = classes;
        cell.textContent = d;
        if (hasData) {{ cell.title = hasData.title; cell.onclick = () => window.location.href = hasData.page; }}
        container.appendChild(cell);
    }}
}}

function initSportCalendar() {{
    const monthSelect = document.getElementById('month-select');
    if (monthSelect) {{
        monthSelect.innerHTML = '';
        sortedMonths.forEach(m => {{
            const [year, month] = m.split('-');
            const opt = document.createElement('option');
            opt.value = m;
            opt.textContent = monthNames[parseInt(month) - 1] + ' ' + year;
            if (m === displayMonth) opt.selected = true;
            monthSelect.appendChild(opt);
        }});
        monthSelect.addEventListener('change', function() {{ renderCalendar(this.value); }});
    }}
    renderCalendar(displayMonth);
    const mobileSelect = document.getElementById('mobile-archive-select');
    if (mobileSelect) {{
        mobileSelect.innerHTML = '<option value="">Select a date...</option>';
        ARCHIVE_DATA.forEach(item => {{
            const opt = document.createElement('option');
            opt.value = item.page;
            const dateObj = new Date(item.date + 'T12:00:00');
            const dateLabel = dateObj.toLocaleDateString('en-US', {{ weekday: 'short', month: 'short', day: 'numeric' }});
            opt.textContent = dateLabel + ' - ' + item.title;
            if (item.page === currentPage) opt.selected = true;
            mobileSelect.appendChild(opt);
        }});
        mobileSelect.addEventListener('change', (e) => {{ if (e.target.value) window.location.href = e.target.value; }});
    }}
}}

if (document.readyState === 'loading') {{ document.addEventListener('DOMContentLoaded', initSportCalendar); }} else {{ initSportCalendar(); }}
'''

    entries_str = ',\n'.join([
        f'    {{ date: "{e["date"]}", page: "{e["page"]}", title: "{e["title"]}" }}'
        for e in entries
    ])

    js_content = js_content.format(
        today=datetime.now().strftime('%Y-%m-%d'),
        entries=entries_str
    )

    output_path = REPO / 'scripts' / 'ncaaf-calendar.js'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"\nGenerated {output_path}")
    print(f"Total entries: {len(entries)}")

if __name__ == '__main__':
    main()
