#!/usr/bin/env python3
"""
Sync Featured Games Data
Automatically updates featured-games-data.js based on existing featured game page files.
This ensures the calendar always reflects all created pages.

Run after creating any featured game page:
    python scripts/sync_featured_games_data.py
"""

import os
import re
import glob
from datetime import datetime

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(REPO_ROOT, 'featured-games-data.js')

def extract_page_info(filepath):
    """Extract date and title from a featured game page."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        # Extract FORCED_PAGE_DATE
        date_match = re.search(r"FORCED_PAGE_DATE\s*=\s*['\"](\d{4}-\d{2}-\d{2})['\"]", content)
        if not date_match:
            return None

        date = date_match.group(1)

        # Extract title - try multiple patterns
        title = None

        # Pattern 1: <title>Sport: Team @ Team - Date | BetLegend</title>
        title_match = re.search(r'<title>([^|<]+?)(?:\s*-\s*[A-Za-z]+\s+\d+,?\s*\d{4})?\s*\|', content)
        if title_match:
            title = title_match.group(1).strip()
            # Clean up "Sport: " prefix for cleaner display
            title = re.sub(r'^(NBA|NHL|NFL|NCAAB|NCAAF|MLB|Soccer):\s*', '', title)

        # Pattern 2: From <h2> matchup
        if not title:
            h2_match = re.search(r'<h2[^>]*>([^<]+)</h2>', content)
            if h2_match:
                title = h2_match.group(1).strip()

        # Fallback to filename
        if not title:
            title = os.path.basename(filepath).replace('.html', '').replace('-', ' ').title()

        return {
            'date': date,
            'page': os.path.basename(filepath),
            'title': title
        }
    except Exception as e:
        print(f"  Error reading {filepath}: {e}")
        return None

def parse_existing_data():
    """Parse existing featured-games-data.js to get current entries."""
    existing = {}
    try:
        with open(DATA_FILE, 'r', encoding='utf-8') as f:
            content = f.read()

        # Find all existing entries
        pattern = r'\{\s*date:\s*"([^"]+)",\s*page:\s*"([^"]+)",\s*title:\s*"([^"]+)"\s*\}'
        for match in re.finditer(pattern, content):
            date, page, title = match.groups()
            # Skip template/placeholder entries
            if date == 'YYYY-MM-DD' or page == 'filename.html':
                continue
            existing[page] = {'date': date, 'page': page, 'title': title}
    except FileNotFoundError:
        pass

    return existing

def generate_data_file(entries):
    """Generate the featured-games-data.js content."""
    # Sort entries by date
    sorted_entries = sorted(entries.values(), key=lambda x: x['date'])

    # Group by month
    months = {}
    for entry in sorted_entries:
        date = datetime.strptime(entry['date'], '%Y-%m-%d')
        month_key = date.strftime('%Y-%m')
        month_name = date.strftime('%B %Y')
        if month_key not in months:
            months[month_key] = {'name': month_name, 'entries': []}
        months[month_key]['entries'].append(entry)

    # Build output
    lines = [
        '// Featured Games Data - Add new entries here when creating new featured game pages',
        '// Format: { date: "YYYY-MM-DD", page: "filename.html", title: "Game Title" }',
        '// The calendar will auto-populate from this data',
        '// AUTO-GENERATED by sync_featured_games_data.py - Manual edits will be preserved',
        '',
        'const FEATURED_GAMES = ['
    ]

    for month_key in sorted(months.keys()):
        month_data = months[month_key]
        lines.append(f'    // {month_data["name"]}')
        for entry in month_data['entries']:
            lines.append(f'    {{ date: "{entry["date"]}", page: "{entry["page"]}", title: "{entry["title"]}" }},')
        lines.append('')

    lines.append('    // ADD NEW FEATURED GAMES HERE (format: date, page, title)')
    lines.append('];')
    lines.append('')
    lines.append('// Export for use in calendar')
    lines.append("if (typeof module !== 'undefined' && module.exports) {")
    lines.append('    module.exports = FEATURED_GAMES;')
    lines.append('}')
    lines.append('')

    return '\n'.join(lines)

def main():
    print("=" * 60)
    print("  FEATURED GAMES DATA SYNC")
    print("=" * 60)

    # Find all featured game pages
    patterns = [
        os.path.join(REPO_ROOT, 'featured-game-of-the-day.html'),
        os.path.join(REPO_ROOT, 'featured-game-of-the-day-page*.html'),
        os.path.join(REPO_ROOT, 'featured-game-of-the-day-*.html'),
    ]

    page_files = set()
    for pattern in patterns:
        page_files.update(glob.glob(pattern))

    print(f"\nFound {len(page_files)} featured game page files")

    # Get existing data
    existing = parse_existing_data()
    print(f"Existing entries in data file: {len(existing)}")

    # Extract info from all pages
    all_entries = {}
    new_count = 0

    for filepath in sorted(page_files):
        info = extract_page_info(filepath)
        if info:
            page_name = info['page']

            # Check if this is a new entry
            if page_name not in existing:
                print(f"  + NEW: {info['date']} - {info['title']} ({page_name})")
                new_count += 1

            # Use existing title if available (preserves manual edits)
            if page_name in existing:
                info['title'] = existing[page_name]['title']

            all_entries[page_name] = info

    # Also keep any entries from data file that might not have matching pages
    # (in case pages were manually added to data file)
    for page_name, entry in existing.items():
        if page_name not in all_entries:
            # Skip template/placeholder entries
            if entry['date'] == 'YYYY-MM-DD' or page_name == 'filename.html':
                continue
            print(f"  ? ORPHAN (in data but no page file): {entry['date']} - {page_name}")
            all_entries[page_name] = entry

    if new_count == 0:
        print("\n[OK] All pages already in data file - no changes needed")
        return

    # Generate and write new data file
    new_content = generate_data_file(all_entries)

    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"\n[OK] Updated {DATA_FILE}")
    print(f"  Added {new_count} new entries")
    print(f"  Total entries: {len(all_entries)}")
    print("\nRemember to commit and push the changes!")

if __name__ == '__main__':
    main()
