- name: Commit and push changes
  env:
    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    git config --global user.name 'github-actions[bot]'
    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    git add matchups.html
    git commit -m "Update matchups" || echo "No changes to commit"
    git push "https://x-access-token:${REPO_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
